; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.21"

; Modules
projects[dyndrop_console][download][type] = "get"
projects[dyndrop_console][download][url] = "https://github.com/dyndrop/dyndrop-console/archive/master.zip"
projects[dyndrop_console][download][subtree] = "dyndrop-console-master/profiles/dyndrop_console"
projects[dyndrop_console][type] = "profile"

projects[admin][version] = "2.x-dev"

projects[ctools][version] = "1.2"

projects[cobalt][version] = "1.0-beta5"

projects[ddbase][download][type] = "get"
projects[ddbase][download][url] = "https://github.com/dyndrop/dyndrop-console/archive/master.zip"
projects[ddbase][download][subtree] = "dyndrop-console-master/modules/ddbase"
projects[ddbase][type] = "module"

projects[ddclient][download][type] = "get"
projects[ddclient][download][url] = "https://github.com/dyndrop/dyndrop-console/archive/master.zip"
projects[ddclient][download][subtree] = "dyndrop-console-master/modules/ddclient"
projects[ddclient][type] = "module"

projects[ddconsole][download][type] = "get"
projects[ddconsole][download][url] = "https://github.com/dyndrop/dyndrop-console/archive/master.zip"
projects[ddconsole][download][subtree] = "dyndrop-console-master/modules/ddconsole"
projects[ddconsole][type] = "module"

projects[features][version] = "2.0-beta1"

projects[flag][version] = "2.0"

projects[globalredirect][version] = "1.5"

projects[http_client][version] = "2.4"
; Do not fail on empty JSON result
projects[http_client][patch][] = http://drupal.org/files/httpclient-json-unserialization.patch

projects[jquery_update][version] = "2.3"

projects[module_filter][version] = "1.7"

projects[nagios][version] = "1.2"

projects[panels][version] = "3.3"

projects[panels_everywhere][version] = "1.0-rc1"

projects[pathauto][version] = "1.2"

projects[redis][version] = "2.0-beta4"
libraries[predis][download][type] = "git"
libraries[predis][download][url] = "git@github.com:nrk/predis.git"
libraries[predis][download][tag] = "v0.8.3"

projects[services][version] = "3.3"

projects[taxonomy_manager][version] = "1.0-rc2"

projects[token][version] = "1.5"

projects[transliteration][version] = "3.1"

projects[varnish][version] = "1.0-beta2"

projects[views][version] = "3.5"

; Themes
projects[bootstrap][version] = "2.0-beta3"

libraries[bootstrap][download][type] = "file"
libraries[bootstrap][download][url] = "http://twitter.github.io/bootstrap/assets/bootstrap.zip"
libraries[bootstrap][destination] = "themes/bootstrap/"

projects[rubik][version] = "4.0-beta8"

projects[tao][version] = "3.0-beta4"

projects[dd_theme][download][type] = "get"
projects[dd_theme][download][url] = "https://github.com/dyndrop/dyndrop-console/archive/master.zip"
projects[dd_theme][download][subtree] = "dyndrop-console-master/themes/dd_theme"
projects[dd_theme][type] = "theme"


