; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.21"

; Modules
projects[dyndrop_console][download][type] = "git"
projects[dyndrop_console][download][url] = "git@github.com:dyndrop/dyndrop-console.git"
projects[dyndrop_console][download][subtree] = "profiles/dyndrop_console"
projects[dyndrop_console][type] = "module"

projects[admin][version] = "2.x-dev"

projects[ctools][version] = "1.2"

projects[cobalt][version] = "1.0-beta5"

projects[ddbase][download][type] = "git"
projects[ddbase][download][url] = "git@github.com:dyndrop/dyndrop-console.git"
projects[ddbase][download][subtree] = "modules/ddbase"
projects[ddbase][type] = "module"

projects[ddclient][download][type] = "git"
projects[ddclient][download][url] = "git@github.com:dyndrop/dyndrop-console.git"
projects[ddclient][download][subtree] = "modules/ddclient"
projects[ddclient][type] = "module"

projects[ddconsole][download][type] = "git"
projects[ddconsole][download][url] = "git@github.com:dyndrop/dyndrop-console.git"
projects[ddconsole][download][subtree] = "modules/ddconsole"
projects[ddconsole][type] = "module"

projects[features][version] = "2.0-beta1"

projects[flag][version] = "2.0"

projects[globalredirect][version] = "1.5"

projects[http_client][version] = "2.4"

projects[jquery_update][version] = "2.3"

projects[module_filter][version] = "1.7"

projects[nagios][version] = "1.2"

projects[panels][version] = "3.3"

projects[panels_everywhere][version] = "1.0-rc1"

projects[pathauto][version] = "1.2"

projects[services][version] = "3.3"

projects[taxonomy_manager][version] = "1.0-rc2"

projects[token][version] = "1.5"

projects[transliteration][version] = "3.1"

projects[views][version] = "3.5"

; Themes
projects[bootstrap][version] = "2.0-beta3"

projects[rubik][version] = "4.0-beta8"

projects[tao][version] = "3.0-beta4"

projects[dd_theme][download][type] = "git"
projects[dd_theme][download][url] = "git@github.com:dyndrop/dyndrop-console.git"
projects[dd_theme][download][subtree] = "themes/dd_theme"
projects[dd_theme][type] = "theme"


