; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.21"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[px][download][type] = ""
projects[px][download][url] = ""
projects[px][type] = "module"

projects[admin][version] = "2.x-dev"

projects[ctools][version] = "1.2"

projects[cobalt][version] = "1.0-beta5"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[Dyndrop][download][type] = ""
projects[Dyndrop][download][url] = ""
projects[Dyndrop][type] = "module"
projects[Dyndrop][version] = "1.0"

projects[features][version] = "2.0-beta1"

projects[flag][version] = "2.0"

projects[globalredirect][version] = "1.5"

projects[http_client][version] = "2.4"

projects[jquery_update][version] = "2.3"

projects[module_filter][version] = "1.7"

projects[nagios][version] = "1.2"

projects[panels][version] = "3.3"

projects[panels_everywhere][version] = "1.0-rc1"

projects[pathauto][version] = "1.2"

projects[services][version] = "3.3"

projects[taxonomy_manager][version] = "1.0-rc2"

projects[token][version] = "1.5"

projects[transliteration][version] = "3.1"

projects[views][version] = "3.5"

; Themes
projects[bootstrap][version] = "2.0-beta3"

projects[rubik][version] = "4.0-beta8"

projects[tao][version] = "3.0-beta4"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[dd_theme][download][type] = ""
projects[dd_theme][download][url] = ""
projects[dd_theme][type] = "theme"


